---
title: 本のタイトル
subtitle: 本の概要
circle: サークル名
author: 本の作者
comiket: コミケ
year: 出版年
publisher: 印刷会社で印刷製本
docrevision: "1.0"
# front: images/front-image.png
#frontoption:
#  - scale=1.25
#  - position=current page.south # bottom of the page
#  - vshift=3cm
#  - angle=0

verbcolored: false
# rmnote: false
#toc-title: "Table of Contents"

svgbob:
  font-family: "Source Code Pro"
  font-size: 14
  scale: 1
  stroke-width: 2

heading-unnumbered:
  1: "Heading Unnumbered 1"
  2: "Heading Unnumbered 2"
  3: "Heading Unnumbered 3"
  4: "Heading Unnumbered 4"
  5: "Heading Unnumbered 4"

heading-appendix:
  1: "Appendix Heading 1"
  2: "Appendix Heading 2"
  3: "Appendix Heading 3"
  4: "Appendix Heading 4"
  5: "Appendix Heading 5"

bullet-style:
  1: "Bullet List 1"
  2: "Bullet List 2"
  3: "Bullet List 3"

numbered-bullets:
  1: "Number Bullet"
  2: "Number Bullet 2"
  3: "Number Bullet 3"

custom-spans:
  red: "WarningTok"
  green: "PreprocessorTok"
  blue: "AttributeTok"

image-div-style: "Image Caption"

docx_coreprop:
  #  author: "K4ZUKI" # str
  #  category: "Category" # str
  #  comments: "Comment" # str
  #  keywords: "Keyword1 Keyword2" # str
  #  last_modified_by: "K4ZUKI" # str
  #  last_printed: "31-Dec-2018" # datetime DD-MMM-YYYY
  #  modified: "31-Dec-2018" # datetime DD-MMM-YYYY
  #  revision: 1123 # int < 32768
  #  subject: "SubjecT" # str
  #  title: "Title" # str

  #  created: "31-Dec-2018" # datetime DD-MMM-YYYY set externally
  #  content_status: "Status" # ignored?
  #  identifier: "ID" # ignored?
  #  language: "Japanese" # ignored?
  #  version: "Version" # ignored?

  table-alignment-in-page: center # left / center /right
  table-cell-vertical-alignment: center # top / center / bottom / both
  read-only-recommended: true
  disable-table-autofit: false # requires explicit column widths setting for *every* table when setting 'true'
  table:
  #    "Normal Table": "Centered"
  paragraph:
    "Image Caption": "Figure Caption"
  #    "Normal": "Body Text"
  #    "First Paragraph": "Body Text"
  character:
...
