name: Build document
on: [ push, create ]
jobs:
  make-firmware:
    name: Compile document
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup safe directory for git
        run: |
          repo=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}
          git config --global --add safe.directory /__w/${repo}/${repo}
      - name: Build firmware (at a tag)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        run: |
          make docker
          make firmware
        with:
          files: pipico-micropython-scpi.uf2
      - name: Upload artifact files (at a push)
        uses: actions/upload-artifact@v3
        with:
          path: |
            micropython/build
